import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { GeistSans } from 'geist/font'
import { GeistMono } from 'geist/font/mono'
import './globals.css'
import { LayoutProvider } from './providers'


// Since these are already instantiated, no need to call them as functions
const geistSans = GeistSans
const geistMono = GeistMono

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export const dynamic = 'force-dynamic';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LayoutProvider>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
          <SignedOut>
            <SignUpButton signInFallbackRedirectUrl="/dashboard">
              <button
                className="px-6 py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-full text-lg font-semibold shadow-lg hover:from-purple-600 hover:to-pink-600 transition-colors"
              >
                Sign Up
              </button>
            </SignUpButton>
            <SignInButton signUpFallbackRedirectUrl="/dashboard">
              <button
                className="px-6 py-3 bg-white/5 border border-white/10 rounded-full text-lg font-semibold shadow-md hover:bg-white/10 transition-colors"
              >
                Sign In
              </button>
            </SignInButton>
          </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </LayoutProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}